<a href="https://colab.research.google.com/github/Huang-23/PRfinal_LSTM/blob/main/nlp_LSTM.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
import numpy as np
import pandas as pd

import jieba.posseg as pseg
import os
import keras

# 讀檔

In [ ]:
TRAIN_CSV_PATH = '/content/drive/MyDrive/nlp_final/train.csv'
TEST_CSV_PATH = '/content/drive/MyDrive/nlp_final/test.csv'

In [ ]:
train = pd.read_csv(TRAIN_CSV_PATH, index_col='id')
train.head(3)

tid1  tid2  ...                                          title2_en      label
id              ...                                                              
0      0     1  ...  Police disprove "bird's nest congress each per...  unrelated
3      2     3  ...  Shenzhen's GDP outstrips Hong Kong? Shenzhen S...  unrelated
1      2     4  ...  The GDP overtopped Hong Kong? Shenzhen clarifi...  unrelated

[3 rows x 7 columns]

In [ ]:
cols = ['title1_zh', 
        'title2_zh', 
        'label']
train = train.loc[:, cols]
train.head(3)

title1_zh                  title2_zh      label
id                                                                         
0       2017养老保险又新增两项，农村老人人人可申领，你领到了吗   警方辟谣“鸟巢大会每人领5万” 仍有老人坚持进京  unrelated
3   "你不来深圳，早晚你儿子也要来"，不出10年深圳人均GDP将超香港  深圳GDP首超香港？深圳统计局辟谣：只是差距在缩小  unrelated
1   "你不来深圳，早晚你儿子也要来"，不出10年深圳人均GDP将超香港       GDP首超香港？深圳澄清：还差一点点……  unrelated

# 文本分詞

In [ ]:
def jieba_tokenizer(text):
    words = pseg.cut(text)
    return ' '.join([
        word for word, flag in words if flag != 'x'])

In [ ]:
train.isna().any()

title1_zh    False
title2_zh     True
label        False
dtype: bool

In [ ]:
train.title2_zh.fillna('UNKNOWN', inplace=True)
train.isna().any()

title1_zh    False
title2_zh    False
label        False
dtype: bool

In [ ]:
def process(data):
    res = data.apply(jieba_tokenizer)
    return res

def check_merge_idx(data, res):
    assert((data.index == res.index).all(), 'Something error when merge data')

def parallelize(data, func):
    from multiprocessing import cpu_count, Pool
    cores = partitions = cpu_count()
    data_split = np.array_split(data, partitions)
    pool = Pool(cores)
    res = pd.concat(pool.map(func, data_split))
    pool.close()
    pool.join()
    check_merge_idx(data, res)
    return res

<ipython-input-9-2085024a8821>:7: SyntaxWarning: assertion is always true, perhaps remove parentheses?
  assert((data.index == res.index).all(), 'Something error when merge data')


In [ ]:
np.all(train.index == train.title1_zh.index)

True

In [ ]:
print("start to training")
train['title1_tokenized'] = parallelize(train.loc[:, 'title1_zh'], process)
train['title2_tokenized'] = parallelize(train.loc[:, 'title2_zh'], process)
#train.to_csv('/content/drive/MyDrive/nlp_final/tokenized_train.csv',index=True)

start to training


Building prefix dict from the default dictionary ...
Building prefix dict from the default dictionary ...
Dumping model to file cache /tmp/jieba.cache
Dumping model to file cache /tmp/jieba.cache
Loading model cost 1.707 seconds.
Prefix dict has been built successfully.
Loading model cost 1.777 seconds.
Prefix dict has been built successfully.
Building prefix dict from the default dictionary ...
Loading model from cache /tmp/jieba.cache
Building prefix dict from the default dictionary ...
Loading model from cache /tmp/jieba.cache
Loading model cost 1.261 seconds.
Prefix dict has been built successfully.
Loading model cost 1.252 seconds.
Prefix dict has been built successfully.


In [ ]:
train.loc[:, ["title1_zh", "title1_tokenized"]].head(10)

title1_zh                                 title1_tokenized
id                                                                                        
0           2017养老保险又新增两项，农村老人人人可申领，你领到了吗         2017 养老保险 又 新增 两项 农村 老人 人人 可 申领 你 领到 了 吗
3       "你不来深圳，早晚你儿子也要来"，不出10年深圳人均GDP将超香港  你 不 来 深圳 早晚 你 儿子 也 要 来 不出 10 年 深圳 人均 GDP 将 超 香港
1       "你不来深圳，早晚你儿子也要来"，不出10年深圳人均GDP将超香港  你 不 来 深圳 早晚 你 儿子 也 要 来 不出 10 年 深圳 人均 GDP 将 超 香港
2       "你不来深圳，早晚你儿子也要来"，不出10年深圳人均GDP将超香港  你 不 来 深圳 早晚 你 儿子 也 要 来 不出 10 年 深圳 人均 GDP 将 超 香港
9                    "用大蒜鉴别地沟油的方法,怎么鉴别地沟油                       用 大蒜 鉴别 地沟油 的 方法 怎么 鉴别 地沟油
4       "你不来深圳，早晚你儿子也要来"，不出10年深圳人均GDP将超香港  你 不 来 深圳 早晚 你 儿子 也 要 来 不出 10 年 深圳 人均 GDP 将 超 香港
6                          "吃榴莲的禁忌,吃错会致命!                                吃 榴莲 的 禁忌 吃 错会 致命
5       "你不来深圳，早晚你儿子也要来"，不出10年深圳人均GDP将超香港  你 不 来 深圳 早晚 你 儿子 也 要 来 不出 10 年 深圳 人均 GDP 将 超 香港
7   "旅行青蛙？居然是一款""生育意愿测试器”！大家还是玩""珠宝V课""吧"        旅行 青蛙 居然 是 一款 生育 意愿 测试 器 大家 还是 玩 珠宝 V 课 吧
8                    "用大蒜鉴别地沟油的方法,怎么鉴别地沟油                       用 大蒜 鉴别 地沟油 的 方法 怎么 鉴别 地沟油

In [ ]:
train.loc[:, ["title2_zh", "title2_tokenized"]].head(10)

title2_zh                           title2_tokenized
id                                                                           
0         警方辟谣“鸟巢大会每人领5万” 仍有老人坚持进京          警方 辟谣 鸟巢 大会 每人 领 5 万 仍 有 老人 坚持 进京
3        深圳GDP首超香港？深圳统计局辟谣：只是差距在缩小         深圳 GDP 首 超 香港 深圳 统计局 辟谣 只是 差距 在 缩小
1             GDP首超香港？深圳澄清：还差一点点……                   GDP 首 超 香港 深圳 澄清 还 差 一点点
2       去年深圳GDP首超香港？深圳统计局辟谣：还差611亿       去年 深圳 GDP 首 超 香港 深圳 统计局 辟谣 还 差 611 亿
9          吃了30年食用油才知道，一片大蒜轻松鉴别地沟油          吃 了 30 年 食用油 才 知道 一片 大蒜 轻松 鉴别 地沟油
4        深圳GDP首超香港？统计局辟谣：未超但差距再度缩小        深圳 GDP 首 超 香港 统计局 辟谣 未 超 但 差距 再度 缩小
6          榴莲不能和什么一起吃 与咖啡同吃诱发心脏病""            榴莲 不能 和 什么 一起 吃 与 咖啡 同 吃 诱发 心脏病
5           深圳GDP首超香港？辟谣：未超但差距再度缩小            深圳 GDP 首 超 香港 辟谣 未 超 但 差距 再度 缩小
7         咸宁一家店的蛋糕含有“棉花”？崇阳多部门联合辟谣           咸宁 一家 店 的 蛋糕 含有 棉花 崇阳 多 部门 联合 辟谣
8   一颗大蒜就能鉴别地沟油？别闹了！做到下面几点，让您远离地沟油  一颗 大蒜 就 能 鉴别 地沟油 别闹 了 做到 下面 几点 让 您 远离 地沟油

In [ ]:
train.fillna('UNKNOWN', inplace=True)

# 建立字典並將文本轉成數字序列
* 將已被斷詞的新聞標題 A 以及新聞標題 B 全部倒在一起
* 建立一個空字典
* 查看所有新聞標題，裏頭每出現一個字典裡頭沒有的詞彙，就為該詞彙指定一個字典裡頭還沒出現的索引數字，並將該詞彙放入字典
* 利用建好的字典，將每個新聞標題裡頭包含的詞彙轉換成數字

In [ ]:
# Keras專門的文字前處理模組
import keras
MAX_NUM_WORDS = 10000  # 限制字典只能包含10,000個詞彙，以避免字典過於龐大
# 將一段文字轉換成一系列的詞彙（Tokens），並為其建立字典
tokenizer = keras \
    .preprocessing \
    .text \
    .Tokenizer(num_words=MAX_NUM_WORDS)

In [ ]:
# 將新聞 A 及新聞 B 的標題全部聚集起來(語料庫)，為它們建立字典
corpus_x1 = train.title1_tokenized
corpus_x2 = train.title2_tokenized
corpus = pd.concat([
    corpus_x1, corpus_x2])
corpus.shape

(641104,)

In [ ]:
# 語料庫的一小部分
pd.DataFrame(corpus.iloc[:5],
             columns=['title'])

title
id                                                 
0          2017 养老保险 又 新增 两项 农村 老人 人人 可 申领 你 领到 了 吗
3   你 不 来 深圳 早晚 你 儿子 也 要 来 不出 10 年 深圳 人均 GDP 将 超 香港
1   你 不 来 深圳 早晚 你 儿子 也 要 来 不出 10 年 深圳 人均 GDP 将 超 香港
2   你 不 来 深圳 早晚 你 儿子 也 要 来 不出 10 年 深圳 人均 GDP 将 超 香港
9                        用 大蒜 鉴别 地沟油 的 方法 怎么 鉴别 地沟油

In [ ]:
corpus.isna().any()

False

In [ ]:
# 呼叫tokenizer查看所有文本，並建立一個字典（2&3）
tokenizer.fit_on_texts(corpus)
# 請tokenizer利用內部生成的字典分別將新聞標題A與B轉換成數字序列
x1_train = tokenizer \
    .texts_to_sequences(corpus_x1)
x2_train = tokenizer \
    .texts_to_sequences(corpus_x2)

In [ ]:
len(x1_train)

320552

In [ ]:
# x1_train為一個Python list，包含了每一筆假新聞標題A對應的數字序列
x1_train[:1]

[[217, 1268, 32, 1178, 5967, 25, 489, 2877, 116, 5559, 4, 1850, 2, 13]]

In [ ]:
# 將索引數字對應回本來的詞彙
for seq in x1_train[:1]:
    print([tokenizer.index_word[idx] for idx in seq])

['2017', '养老保险', '又', '新增', '两项', '农村', '老人', '人人', '可', '申领', '你', '领到', '了', '吗']


# 序列的 Zero Padding

In [ ]:
# 長度超過此數字的序列尾巴會被刪掉；而針對原來長度不足的序列則會在詞彙前面補零
MAX_SEQUENCE_LENGTH = 20
x1_train = keras \
    .preprocessing \
    .sequence \
    .pad_sequences(x1_train, 
                   maxlen=MAX_SEQUENCE_LENGTH)

x2_train = keras \
    .preprocessing \
    .sequence \
    .pad_sequences(x2_train, 
                   maxlen=MAX_SEQUENCE_LENGTH)

In [ ]:
x1_train[0]

array([   0,    0,    0,    0,    0,    0,  217, 1268,   32, 1178, 5967,
         25,  489, 2877,  116, 5559,    4, 1850,    2,   13], dtype=int32)

In [ ]:
for seq in x1_train + x2_train:
    assert len(seq) == 20
    
print("所有新聞標題的序列長度皆為 20 !")

所有新聞標題的序列長度皆為 20 !


# 將 Label 做 One-hot Encoding

In [ ]:
train.label[:5]

id
0    unrelated
3    unrelated
1    unrelated
2    unrelated
9       agreed
Name: label, dtype: object

In [ ]:
# 需要一個字典將分類的文字轉換成索引
import numpy as np 

# 定義每一個分類對應到的索引數字
label_to_index = {
    'unrelated': 0, 
    'agreed': 1, 
    'disagreed': 2
}

# 將分類標籤對應到剛定義的數字
y_train = train.label.apply(
    lambda x: label_to_index[x])

y_train = np.asarray(y_train) \
            .astype('float32')

y_train[:5]

array([0., 0., 0., 0., 1.], dtype=float32)

In [ ]:
x1_train[:5]

array([[   0,    0,    0,    0,    0,    0,  217, 1268,   32, 1178, 5967,
          25,  489, 2877,  116, 5559,    4, 1850,    2,   13],
       [   0,    4,   10,   47,  678, 2558,    4,  166,   34,   17,   47,
        5150,   63,   15,  678, 4502, 3211,   23,  284, 1181],
       [   0,    4,   10,   47,  678, 2558,    4,  166,   34,   17,   47,
        5150,   63,   15,  678, 4502, 3211,   23,  284, 1181],
       [   0,    4,   10,   47,  678, 2558,    4,  166,   34,   17,   47,
        5150,   63,   15,  678, 4502, 3211,   23,  284, 1181],
       [   0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          31,  320, 3372, 3062,    1,   95,   98, 3372, 3062]],
      dtype=int32)

In [ ]:
train.label[:5]

id
0    unrelated
3    unrelated
1    unrelated
2    unrelated
9       agreed
Name: label, dtype: object

In [ ]:
# 利用 Keras 做 One Hot Encoding
# [1, 0, 0] 就代表一組新聞標題 A、B 為 unrelated 的機率等於 100 %
from keras.utils import np_utils

y_train = keras \
    .utils \
    .np_utils \
    .to_categorical(y_train)

y_train[:5]

array([[1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.]], dtype=float32)

# 切割訓練 & 驗證資料集

In [ ]:
from sklearn.model_selection \
    import train_test_split

VALIDATION_RATIO = 0.1  # 決定要將整個訓練資料集的多少比例切出來當作驗證資料集
RANDOM_STATE = 9527

x1_train, x1_val, \
x2_train, x2_val, \
y_train, y_val = \
    train_test_split(
        x1_train, x2_train, y_train, 
        test_size=VALIDATION_RATIO, 
        random_state=RANDOM_STATE
)

In [ ]:
print("Training Set")
print("-" * 10)
print(f"x1_train: {x1_train.shape}")
print(f"x2_train: {x2_train.shape}")
print(f"y_train : {y_train.shape}")

print("-" * 10)
print(f"x1_val:   {x1_val.shape}")
print(f"x2_val:   {x2_val.shape}")
print(f"y_val :   {y_val.shape}")
print("-" * 10)
print("Test Set")

Training Set
----------
x1_train: (288496, 20)
x2_train: (288496, 20)
y_train : (288496, 3)
----------
x1_val:   (32056, 20)
x2_val:   (32056, 20)
y_val :   (32056, 3)
----------
Test Set


# 此模型的 Keras 實作

In [ ]:
# 基本參數設置，有幾個分類
NUM_CLASSES = 3

# 在語料庫裡有多少詞彙
MAX_NUM_WORDS = 10000

# 一個標題最長有幾個詞彙
MAX_SEQUENCE_LENGTH = 20

# 一個詞向量的維度
NUM_EMBEDDING_DIM = 256

# LSTM 輸出的向量維度
NUM_LSTM_UNITS = 128

In [ ]:
# 建立孿生 LSTM 架構（Siamese LSTM）
from keras import Input
from keras.layers import Embedding,LSTM, concatenate, Dense
from keras.models import Model

# 分別定義 2 個新聞標題 A & B 為模型輸入
# 兩個標題都是一個長度為 20 的數字序列
top_input = Input(
    shape=(MAX_SEQUENCE_LENGTH, ), 
    dtype='int32')
bm_input = Input(
    shape=(MAX_SEQUENCE_LENGTH, ), 
    dtype='int32')

# 詞嵌入層（Word Embedding）
# 經過詞嵌入層的轉換，兩個新聞標題都變成一個詞向量的序列，而每個詞向量的維度為256
from keras.layers import Embedding
embedding_layer = Embedding(
    MAX_NUM_WORDS, NUM_EMBEDDING_DIM)
top_embedded = embedding_layer(
    top_input)
bm_embedded = embedding_layer(
    bm_input)

# LSTM 層
# 兩個新聞標題經過此層後為一個 128 維度向量
shared_lstm = LSTM(NUM_LSTM_UNITS)
top_output = shared_lstm(top_embedded)
bm_output = shared_lstm(bm_embedded)

# 串接層將兩個新聞標題的結果串接單一向量
# 方便跟全連結層相連
merged = concatenate(
    [top_output, bm_output], 
    axis=-1)

# 全連接層搭配 Softmax Activation
# 可以回傳 3 個成對標題
# 屬於各類別的可能機率
dense =  Dense(
    units=NUM_CLASSES, 
    activation='softmax')
predictions = dense(merged)

# 模型就是將數字序列的輸入，轉換成3個分類的機率的所有步驟 / 層的總和
model = Model(
    inputs=[top_input, bm_input], 
    outputs=predictions)

# 看每一層的參數量以及輸出的張量（Tensor）長相
model.summary()

Model: "model"
__________________________________________________________________________________________________
Layer (type)                    Output Shape         Param #     Connected to                     
input_1 (InputLayer)            [(None, 20)]         0                                            
__________________________________________________________________________________________________
input_2 (InputLayer)            [(None, 20)]         0                                            
__________________________________________________________________________________________________
embedding (Embedding)           (None, 20, 256)      2560000     input_1[0][0]                    
                                                                 input_2[0][0]                    
__________________________________________________________________________________________________
lstm (LSTM)                     (None, 128)          197120      embedding[0][0]              

In [ ]:
x1_train[:9527].shape

(9527, 20)

In [ ]:
from keras.optimizers import adam_v2

In [ ]:
lr = 1e-3
opt = adam_v2.Adam(lr=lr, decay=lr/50)
# 定義模型的損失函數
model.compile(
    optimizer='adam',
    loss='categorical_crossentropy',
    metrics=['accuracy'])

/usr/local/lib/python3.7/dist-packages/keras/optimizer_v2/optimizer_v2.py:356: UserWarning: The `lr` argument is deprecated, use `learning_rate` instead.
  "The `lr` argument is deprecated, use `learning_rate` instead.")


# 訓練模型並挑選最好的結果

In [ ]:
# 決定一次要放多少成對標題給模型訓練
BATCH_SIZE = 1024

# 決定模型要看整個訓練資料集幾遍
NUM_EPOCHS = 500

# 實際訓練模型
history = model.fit(
    # 輸入是兩個長度為 20 的數字序列
    x=[x1_train, x2_train], 
    y=y_train,
    batch_size=BATCH_SIZE,
    epochs=NUM_EPOCHS,
    # 每個 epoch 完後計算驗證資料集
    # 上的 Loss 以及準確度
    validation_data=(
        [x1_val, x2_val], 
        y_val
    ),
    # 每個 epoch 隨機調整訓練資料集
    # 裡頭的數據以讓訓練過程更穩定
    shuffle=True
)

Epoch 1/500
282/282 [==============================] - 18s 37ms/step - loss: 0.4936 - accuracy: 0.7748 - val_loss: 0.4057 - val_accuracy: 0.8124
Epoch 2/500
282/282 [==============================] - 10s 34ms/step - loss: 0.3682 - accuracy: 0.8335 - val_loss: 0.3825 - val_accuracy: 0.8292
Epoch 3/500
282/282 [==============================] - 10s 34ms/step - loss: 0.3350 - accuracy: 0.8500 - val_loss: 0.3756 - val_accuracy: 0.8340
Epoch 4/500
282/282 [==============================] - 10s 34ms/step - loss: 0.3093 - accuracy: 0.8640 - val_loss: 0.3744 - val_accuracy: 0.8368
Epoch 5/500
282/282 [==============================] - 10s 34ms/step - loss: 0.2872 - accuracy: 0.8746 - val_loss: 0.3810 - val_accuracy: 0.8394
Epoch 6/500
282/282 [==============================] - 10s 34ms/step - loss: 0.2696 - accuracy: 0.8828 - val_loss: 0.3769 - val_accuracy: 0.8427
Epoch 7/500
282/282 [==============================] - 10s 34ms/step - loss: 0.2497 - accuracy: 0.8920 - val_loss: 0.3832 - val_ac

# 進行預測並提交結果

In [ ]:
print("Use raw test csv")
test = pd.read_csv(TEST_CSV_PATH, index_col=0)
test.fillna('UNKNOWN', inplace=True)
test['title1_tokenized'] = parallelize(test.loc[:, 'title1_zh'], process)
test['title2_tokenized'] = parallelize(test.loc[:, 'title2_zh'], process)
test.fillna('UNKNOWN', inplace=True)
test.head(3)

Use raw test csv


Building prefix dict from the default dictionary ...
Loading model from cache /tmp/jieba.cache
Building prefix dict from the default dictionary ...
Loading model from cache /tmp/jieba.cache
Loading model cost 1.295 seconds.
Prefix dict has been built successfully.
Loading model cost 1.311 seconds.
Prefix dict has been built successfully.
Building prefix dict from the default dictionary ...
Loading model from cache /tmp/jieba.cache
Building prefix dict from the default dictionary ...
Loading model from cache /tmp/jieba.cache
Loading model cost 1.148 seconds.
Prefix dict has been built successfully.
Loading model cost 1.202 seconds.
Prefix dict has been built successfully.


tid1  ...                        title2_tokenized
id              ...                                        
321187  167562  ...    辟谣 里昂 官方 否认 费 基尔 加盟 利物浦 难道 是 价格 没 谈拢
321190  167564  ...  10 大 最 让 美国 人 相信 的 荒诞 谣言 如 蜥蜴人 掌控 着 美国
321189  167563  ...              萨达姆 被捕 后 告诫 美国 的 一句 话 发人深思

[3 rows x 8 columns]

In [ ]:
test.insert(4, column="label", value="")
test.head(3)

tid1  ...                        title2_tokenized
id              ...                                        
321187  167562  ...    辟谣 里昂 官方 否认 费 基尔 加盟 利物浦 难道 是 价格 没 谈拢
321190  167564  ...  10 大 最 让 美国 人 相信 的 荒诞 谣言 如 蜥蜴人 掌控 着 美国
321189  167563  ...              萨达姆 被捕 后 告诫 美国 的 一句 话 发人深思

[3 rows x 9 columns]

In [ ]:
cols = ['title1_zh', 
        'title2_zh', 
        'label',
        'title1_tokenized',
        'title2_tokenized']
test = test.loc[:, cols]
test.head(3)

title1_zh  ...                        title2_tokenized
id                                       ...                                        
321187  萨拉赫人气爆棚!埃及总统大选未参选获百万选票 现任总统压力山大  ...    辟谣 里昂 官方 否认 费 基尔 加盟 利物浦 难道 是 价格 没 谈拢
321190              萨达姆被捕后告诫美国的一句话，发人深思  ...  10 大 最 让 美国 人 相信 的 荒诞 谣言 如 蜥蜴人 掌控 着 美国
321189    萨达姆此项计划没有此国破坏的话，美国还会对伊拉克发动战争吗  ...              萨达姆 被捕 后 告诫 美国 的 一句 话 发人深思

[3 rows x 5 columns]

In [ ]:
# 將詞彙序列轉為索引數字的序列
x1_test = tokenizer \
    .texts_to_sequences(
        test.title1_tokenized)
x2_test = tokenizer \
    .texts_to_sequences(
        test.title2_tokenized)

# 為數字序列加入 zero padding
x1_test = keras \
    .preprocessing \
    .sequence \
    .pad_sequences(
        x1_test, 
        maxlen=MAX_SEQUENCE_LENGTH)
x2_test = keras \
    .preprocessing \
    .sequence \
    .pad_sequences(
        x2_test, 
        maxlen=MAX_SEQUENCE_LENGTH)    

# 利用已訓練的模型做預測
predictions = model.predict(
    [x1_test, x2_test])

In [ ]:
# 從模型得到的預測結果
# 會回傳給我們 3 個分類的機率值
predictions[:5]

array([[1.0000000e+00, 1.7628143e-19, 4.3848384e-16],
       [1.0000000e+00, 5.4379916e-21, 1.5212559e-12],
       [9.9990010e-01, 9.9930898e-05, 5.1073485e-13],
       [1.0000000e+00, 1.1076470e-22, 2.5842076e-19],
       [1.0000000e+00, 1.0157090e-15, 1.1334577e-11]], dtype=float32)

In [ ]:
# 將機率值最大的類別當作答案，並將這個結果轉回對應的文本標籤
index_to_label = {v: k for k, v in label_to_index.items()}

test['Category'] = [index_to_label[idx] for idx in np.argmax(predictions, axis=1)]

submission = test \
    .loc[:, ['Category']] \
    .reset_index()

submission.columns = ['Id', 'Category']
submission.to_csv('/content/drive/MyDrive/nlp_final/submission.csv', index=False)
submission.head()

Id   Category
0  321187  unrelated
1  321190  unrelated
2  321189  unrelated
3  321193  unrelated
4  321191  unrelated